-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Anamakine: 127.0.0.1
-- Üretim Zamanı: 06 Oca 2025, 02:00:46
-- Sunucu sürümü: 8.3.0
-- PHP Sürümü: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Veritabanı: `sinema`
--

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `filmler`
--

CREATE TABLE `filmler` (
  `id` int NOT NULL,
  `baslik` varchar(255) NOT NULL,
  `yonetmen` varchar(255) NOT NULL,
  `yil` int NOT NULL,
  `tur` varchar(100) NOT NULL,
  `afis` varchar(255) NOT NULL,
  `eklenme_tarihi` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `aciklama` text,
  `user_id` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Tablo döküm verisi `filmler`
--

INSERT INTO `filmler` (`id`, `baslik`, `yonetmen`, `yil`, `tur`, `afis`, `eklenme_tarihi`, `aciklama`, `user_id`) VALUES
(1, 'İnception', 'Christopher Nolan', 2010, 'Bilim Kurgu', 'afisler/inception-0-1000-0-1500-crop.jpg', '2024-10-23 10:38:21', 'Zihniniz suç mahallidir.\r\nHedeflerinin bilinçaltına sızarak şirket casusluğu yapan yetenekli bir hırsız olan Cobb\'a, imkansız olduğu düşünülen bir görevin bedeli olarak eski hayatını geri kazanma şansı sunulur: “Başlangıç”, başka bir kişinin fikrinin bir hedefin bilinçaltına yerleştirilmesi.', NULL),
(2, 'Blade Runner', 'Ridley Scott', 1982, 'Bilim Kurgu', 'afisler/vfzE3pjE5G7G7kcZWrA3fnbZo7V-0-1000-0-1500-crop.jpg', '2024-10-23 10:48:57', 'İnsanoğlu eşini buldu... şimdi bu onun sorunu.\r\n2019un dumanlı distopik Los Angelesında, bıçak koşucusu Rick Deckard, kısa ömürlerini uzatmanın bir yolunu bulmak için yaratıcılarını arayan ve Dünyaya kaçan bir dörtlü replikantı yok etmek için emekliliğinden çağrılır.', NULL),
(3, 'Apocalypse Now', 'Francis Ford Coppola', 1979, 'Savaş', 'afisler/2690-apocalypse-now-0-1000-0-1500-crop.jpg', '2024-10-23 11:05:10', 'This is the end...\r\n\r\nYüzbaşı Benjamin Willard, Vietnam Savaşı\'nın en şiddetli günlerinde, resmi olarak “var olmayan ve hiçbir zaman da var olmayacak” tehlikeli bir göreve gönderilir. Amacı, kişisel ordusunu düşman topraklarında yasadışı gerilla görevlerine götüren Walter Kurtz adlı gizemli bir Yeşil Bereli Albay\'ın yerini tespit etmek ve onu ortadan kaldırmaktır.', NULL),
(4, 'Fight Club', 'David Fincher', 1999, 'Dram', 'afisler/51568-fight-club-0-1000-0-1500-crop.jpg', '2024-10-24 19:47:28', 'Yaramazlık. Kargaşa. Sabun. Zaman ayarlı bir uykusuzluk hastası ve kaypak bir sabun satıcısı, ilkel erkek saldırganlığını şok edici yeni bir terapi biçimine yönlendirir. Konseptleri tutulur ve her kasabada yeraltı “dövüş kulüpleri” kurulur, ta ki bir eksantrik yollarına çıkıp kontrolden çıkıp unutulmaya doğru bir sarmalın fitilini ateşleyene kadar.', NULL),
(5, 'Interstellar', 'Christopher Nolan', 2014, 'Bilim Kurgu', 'afisler/117621-interstellar-0-1000-0-1500-crop.jpg', '2024-10-24 19:48:50', 'İnsanoğlu Dünya\'da doğdu. Burada ölmek için yaratılmamıştı.\r\nYeni keşfedilen bir solucan deliğinden yararlanarak insanoğlunun uzay yolculuğundaki sınırlamaları aşan ve yıldızlararası bir yolculukla ilgili engin mesafeleri fetheden bir grup kaşifin maceraları.', NULL),
(6, 'Pulp Fiction', 'Quentin Tarantino', 1994, 'Suç', 'afisler/51444-pulp-fiction-0-1000-0-1500-crop.jpg', '2024-10-24 19:50:13', 'Kurguyu görmeden gerçekleri bilemezsiniz.\r\nHamburger seven bir kiralık katil, onun filozof ortağı, uyuşturucu bağımlısı bir gangsterin fahişesi ve bitkin bir boksör bu geniş kapsamlı, komedi dolu suç oyununda bir araya geliyor. Maceraları, zamanda ustaca ileri geri yolculuk yapan üç öyküde ortaya çıkıyor.', NULL),
(7, 'Forrest Gump', ' Robert Zemeckis', 1994, 'Dram', 'afisler/2704-forrest-gump-0-1000-0-1500-crop.jpg', '2024-10-24 19:52:15', 'The world will never be the same once you’ve seen it through the eyes of Forrest Gump.\r\nA man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.', NULL),
(8, 'Stalker', 'Andrei Tarkovsky', 1979, 'Dram', 'afisler/51062-stalker-0-1000-0-1500-crop.jpg', '2024-10-24 19:53:23', 'Gri ve isimsiz bir şehrin yakınında, dikenli teller ve askerler tarafından korunan ve normal fizik kurallarının sık sık anomalilere kurban gittiği bir yer olan Bölge vardır. Bir takipçi, iki adamı Bölge\'ye, özellikle de derinlerde yatan arzuların gerçekleştiği bir alana yönlendirir.', NULL),
(9, 'Come and See', 'Elem Klimov', 1985, 'Savaş', 'afisler/36192-come-and-see-0-1000-0-1500-crop.jpg', '2024-10-24 19:54:29', 'To love… to have children.\r\nAlman güçlerinin Beyaz Rusya\'daki bir köyü işgali, genç Florya\'yı ailesinin isteğine rağmen yorgun Direniş savaşçılarına katılması için ormana gönderir. Orada Glasha adında bir kızla tanışır ve kız ona köyüne kadar eşlik eder. Florya eve döndüğünde ailesini ve köylü arkadaşlarını katledilmiş olarak bulur. Savaşın acımasız enkazının ortasında hayatta kalmaya devam etmesi, umutsuzluk ve umut arasında bir savaş olarak giderek kabusa dönüşür.', NULL),
(10, 'The Godfather', 'Francis Ford Coppola', 1972, 'Suç', 'afisler/51818-the-godfather-0-1000-0-1500-crop.jpg', '2024-10-24 19:55:40', 'Reddedemeyeceğiniz bir teklif.\r\n1945 ile 1955 yılları arasını kapsayan, İtalyan-Amerikan Corleone suç ailesinin kurgusal öyküsü. Organize suç ailesinin reisi Vito Corleone, hayatına kastedilmesinden kıl payı kurtulunca, en küçük oğlu Michael, katillerin icabına bakmak için devreye girer ve kanlı bir intikam kampanyası başlatır.', NULL),
(11, 'Eternal Sunshine of the Spotless Mind', 'Michel Gondry', 2004, 'Romantik', 'afisler/uBfQ7IGpi0jXSP3GPCzp9Pzm10v-0-1000-0-1500-crop.jpg', '2024-10-24 19:56:50', 'Birini aklınızdan silebilirsiniz. Onları kalbinizden çıkarmak ise bambaşka bir hikâye.\r\nJoel Barish, kız arkadaşının kendisini hafızasından silmek için bir işlem yaptırmasına çok üzülür ve aynısını yapmaya karar verir. Ancak onunla ilgili anılarının yok oluşunu izlerken, onu hâlâ sevdiğini ve hatasını düzeltmek için çok geç kalmış olabileceğini fark eder.', NULL),
(12, 'The Silence of the Lambs', 'Jonathan Demme', 1991, 'Korku', 'afisler/51782-the-silence-of-the-lambs-0-1000-0-1500-crop.jpg', '2024-10-24 19:57:55', 'Bir katilin zihnine girmek için bir delinin zihnine meydan okumalıdır.\r\nClarice Starling, FBI\'ın eğitim akademisinde en iyi öğrencilerden biridir. Jack Crawford, Clarice\'ten, aynı zamanda vahşi bir psikopat olan ve çeşitli cinayet ve yamyamlık eylemleri nedeniyle ömür boyu hapis cezasına çarptırılan parlak bir psikiyatrist olan Dr. Hannibal Lecter ile görüşmesini ister. Crawford, Lecter\'ın bir dava hakkında bilgi sahibi olabileceğine ve Starling\'in de çekici bir genç kadın olarak Lecter\'ı ortaya çıkaracak yem olabileceğine inanmaktadır.', NULL),
(13, 'No Country for Old Men', 'Joel Coen, Ethan Coen', 2007, 'Gerilim', 'afisler/ehLb2SQ3djlA1FrQKbP2WO3VH09-0-1000-0-1500-crop.jpg', '2024-10-24 19:58:53', 'Temiz kaçış yoktur.\r\nLlewelyn Moss, Teksas çölünde cesetlere, 2 milyon dolara ve bir eroin deposuna rastlar, ancak metodik katil Anton Chigurh, yerel şerif Ed Tom Bell\'in peşine düşer. Para ve adaletin şiddetli arayışı çarpışırken av ve avcı rolleri bulanıklaşır.', NULL),
(14, 'Memories of Murder', 'Bong Joon-ho', 2003, 'Suç', 'afisler/gawnVe9cFowdoDLo9Pok12NTw39-0-1000-0-1500-crop.jpg', '2024-10-24 20:00:16', 'En kötüleri sizinle kalacak... sonsuza dek.\r\n1980\'lerin sonlarında, Güney Kore\'nin bir eyaletinde iki dedektif ülkenin ilk tecavüz ve cinayet vakalarını çözmeye çalışır.', NULL),
(15, 'The Thing', 'John Carpenter', 1982, 'Korku', 'afisler/s5fH3GqFcHbi2F0NSBSh4KRNTc0-0-1000-0-1500-crop.jpg', '2024-10-24 20:01:26', 'İnsan saklanmak için en sıcak yerdir.\r\n1982 kışında, Antarktika\'daki uzak bir araştırma istasyonunda on iki kişilik bir araştırma ekibi, 100.000 yıldan uzun süredir karda gömülü olan bir uzaylı keşfeder. Kısa süre sonra donmuş halde bulunan bu şekil değiştiren yaratık ortalığı kasıp kavurur, dehşet saçar... ve onlardan biri haline gelir.', NULL),
(16, 'GoodFellas', 'Martin Scorsese', 1990, 'Suç', 'afisler/51383-goodfellas-0-1000-0-1500-crop.jpg', '2024-10-24 20:04:27', 'Mafya hayatının otuz yılı.\r\nYarı İrlandalı, yarı Sicilyalı Brooklynli bir çocuk olan Henry Hill\'in küçük yaşta mahalle gangsterleri tarafından evlat edinilmesi ve Jimmy Conway\'in rehberliğinde bir mafya ailesinin basamaklarını tırmanmasının gerçek hikayesi.', NULL),
(17, 'The Dark Knight', 'Christopher Nolan', 2008, 'Aksiyon', 'afisler/oefdD26aey8GPdx7Rm45PNncJdU-0-1000-0-1500-crop.jpg', '2024-10-24 20:05:41', 'Kuralsız bir dünyaya hoş geldiniz.\r\nBatman suça karşı savaşında çıtayı yükseltiyor. Batman, Teğmen Jim Gordon ve Bölge Savcısı Harvey Dent\'in yardımıyla, sokakları kasıp kavuran suç örgütlerini çökertmek için yola koyulur. Ortaklığın etkili olduğu kanıtlanır, ancak kısa süre sonra kendilerini Gotham\'ın dehşete düşmüş vatandaşları tarafından Joker olarak bilinen yükselen bir suç dehası tarafından serbest bırakılan bir kaos saltanatının avı olarak bulurlar.', NULL),
(18, 'Whiplash', 'Whiplash', 2014, 'Müzikal', 'afisler/4C9LHDxMsoYI0S3iMPZdm3Oevwo-0-1000-0-1500-crop.jpg', '2024-10-25 07:09:06', 'Mükemmelliğe giden yol sizi uçurumun kenarına götürebilir.\r\nAcımasız bir eğitmenin yönlendirmesi altında, yetenekli genç bir davulcu ne pahasına olursa olsun, hatta insanlığı pahasına mükemmelliğin peşinden gitmeye başlar.', NULL),
(19, 'The Shining', 'Stanley Kubrick', 1980, 'Korku', 'afisler/caoYMcjUamGoBVy65i1AHJBvdzw-0-1000-0-1500-crop.jpg', '2024-10-25 07:12:04', 'Modern korkunun başyapıtı.\r\nJack Torrance, karısı Wendy ve oğulları Danny ile birlikte kış boyunca dünyanın geri kalanından izole bir şekilde yaşamak zorunda olduğu Overlook Oteli\'nde bekçilik işini kabul eder. Ancak içeride gizlenen deliliğe hazırlıklı değillerdir.', NULL),
(20, 'The Truman Show', 'Peter Weir', 1998, 'Komedi', 'afisler/the-truman-show-0-1000-0-1500-crop.jpg', '2024-10-25 07:12:54', 'Yayında. Farkında olmadan.\r\nTruman Burbank, doğduğu andan itibaren, son otuz yıldır her günün her saniyesinde, tarihin en uzun soluklu, en popüler belgesel-soap operasının farkında olmadan yıldızı olmuştur. Ev olarak adlandırdığı mükemmel Seahaven kasabası aslında devasa bir ses sahnesi. Truman\'ın arkadaşları ve ailesi -aslında tanıştığı herkes- birer oyuncu. Her anını binlerce gizli TV kamerasının göz kırpmayan bakışları altında yaşıyor.', NULL),
(21, 'The Matrix', 'Lana Wachowski, Lilly Wachowski', 1999, 'Bilim Kurgu', 'afisler/51518-the-matrix-0-1000-0-1500-crop.jpg', '2024-10-25 07:13:45', 'Gelecek için mücadele başlıyor.\r\n22. yüzyılda geçen Matrix, artık dünyayı yöneten devasa ve güçlü bilgisayarlara karşı savaşan bir grup yeraltı isyancısına katılan bir bilgisayar korsanının hikayesini anlatıyor.', NULL),
(22, 'Taxi Driver', 'Martin Scorsese', 1976, 'Suç', 'afisler/51947-taxi-driver-0-1000-0-1500-crop.jpg', '2024-10-25 07:15:05', 'Her şehrin her sokağında, önemli biri olmayı hayal eden bir hiç kimse vardır.\r\nAkli dengesi yerinde olmayan bir Vietnam Savaşı gazisi, New York\'ta gece taksi şoförü olarak çalışmaktadır ve burada algılanan çöküş ve adilik onun şiddet eylemi dürtüsünü beslemektedir.', NULL),
(23, 'La La Land', 'Damien Chazelle', 2016, 'Romantik', 'afisler/240344-la-la-land-0-1000-0-1500-crop.jpg', '2024-10-25 07:19:05', 'Hayal kuran aptalların şerefine.\r\nHevesli bir aktris olan Mia, seçmeler arasında film yıldızlarına latte servisi yapmakta, caz müzisyeni Sebastian ise köhne barlarda kokteyl partisi konserleri vererek geçinmektedir; ancak başarı arttıkça, aşk ilişkilerinin kırılgan dokusunu yıpratmaya başlayan kararlarla karşı karşıya kalırlar ve birbirlerinde sürdürmek için çok çalıştıkları hayaller onları parçalamakla tehdit eder.', NULL),
(24, 'Parasite', 'Bong Joon-ho', 2019, 'Gerilim', 'afisler/426406-parasite-0-1000-0-1500-crop.jpg', '2024-10-25 07:22:06', 'Buranın sahibiymiş gibi davran.\r\nHepsi işsiz olan Ki-taek\'in ailesi, geçimlerini sağlamak için zengin ve göz alıcı Parks\'a özel bir ilgi duyar, ta ki beklenmedik bir olaya karışana kadar.', NULL),
(25, 'Se7en', 'David Fincher', 1995, 'Suç', 'afisler/51345-se7en-0-1000-0-1500-crop.jpg', '2024-10-25 07:24:31', 'Yedi ölümcül günah. Ölmenin yedi yolu.\r\nİki cinayet masası dedektifi, izleyicileri bir kurbanın işkence görmüş kalıntılarından diğerine götüren bu karanlık ve akıldan çıkmayan filmde, suçları “yedi ölümcül günaha” dayanan bir seri katilin umutsuzca peşine düşüyor. Tecrübeli Dedektif Sommerset, katilin zihnine girebilmek için her bir günahı araştırırken, acemi ortağı Mills onun davayı çözme çabalarıyla alay eder.', NULL),
(26, 'Oppenheimer', 'Christopher Nolan', 2023, 'Tarih', 'afisler/784328-oppenheimer-0-1000-0-1500-crop.jpg', '2024-10-25 07:26:43', 'Dünya sonsuza dek değişiyor.\r\nJ. Robert Oppenheimer\'ın İkinci Dünya Savaşı sırasında atom bombasının geliştirilmesindeki rolünün öyküsü.', NULL),
(27, 'The Shawshank Redemption', 'Frank Darabont', 1994, 'Dram', 'afisler/zGINvGjdlO6TJRu9wESQvWlOKVT-0-1000-0-1500-crop.jpg', '2024-10-25 07:28:03', 'Korku sizi tutsak edebilir. Umut sizi özgür bırakabilir.\r\n1940\'larda karısı ve sevgilisini çifte cinayetten hapse atılan dürüst bankacı Andy Dufresne, Shawshank hapishanesinde yeni bir hayata başlar ve burada muhasebe becerilerini ahlaksız bir müdür için kullanır. Hapishanede geçirdiği uzun süre boyunca Dufresne, dürüstlüğü ve sönmeyen umut duygusu nedeniyle Red adında yaşlı bir mahkûm da dahil olmak üzere diğer mahkûmlar tarafından takdir edilir.', NULL),
(28, 'Blade Runner 2049', 'Denis Villeneuve', 2017, 'Bilim Kurgu', 'afisler/265439-blade-runner-2049-0-1000-0-1500-crop.jpg', '2024-10-25 07:43:14', 'Geleceğin anahtarı nihayet ortaya çıkarılıyor.\r\nİlk filmdeki olaylardan otuz yıl sonra, yeni bir blade runner olan LAPD Memuru K, toplumdan geriye kalanları kaosa sürükleme potansiyeline sahip uzun zamandır gömülü bir sırrı ortaya çıkarır. K\'nın keşfi, onu 30 yıldır kayıp olan eski LAPD blade runner\'ı Rick Deckard\'ı bulma arayışına yönlendirir.', NULL),
(29, 'Joker', 'Todd Phillips', 2019, 'Suç', 'afisler/406775-joker-0-1000-0-1500-crop.jpg', '2024-10-25 07:43:59', 'Mutlu bir yüz takın.\r\n1980\'lerde, başarısız bir stand-up komedyeni delirir ve Gotham Şehri\'nde suç ve kaos dolu bir hayata yönelirken, kötü şöhretli bir psikopat suç figürü haline gelir.', NULL),
(30, 'The Wolf of Wall Street', 'Martin Scorsese', 2013, 'Komedi', 'afisler/86114-the-wolf-of-wall-street-0-1000-0-1500-crop.jpg', '2024-10-25 07:44:45', 'Kazan. Harca. Parti.\r\nNew Yorklu bir borsacı, Wall Street\'teki yolsuzlukları, kurumsal bankacılık dünyasını ve mafyanın sızmasını içeren büyük bir menkul kıymet dolandırıcılığı davasında işbirliği yapmayı reddeder. Jordan Belfort\'un otobiyografisinden uyarlanmıştır.\r\n', NULL),
(31, 'Spirited Away', 'Hayao Miyazaki', 2001, 'Animasyon', 'afisler/51921-spirited-away-0-1000-0-1500-crop.jpg', '2024-10-25 07:45:48', 'Genç bir kız olan Chihiro, yeni ve tuhaf bir ruhlar dünyasında kapana kısılır. Ailesi gizemli bir dönüşüm geçirdiğinde, ailesini kurtarmak için sahip olduğunu hiç bilmediği cesaretini çağırmalıdır.\r\n', NULL),
(32, 'Dead Poets Society', 'Peter Weir', 1989, 'Drama', 'afisler/51846-dead-poets-society-0-1000-0-1500-crop.jpg', '2024-10-25 07:46:28', 'O onların ilham kaynağıydı. Hayatlarını olağanüstü hale getirdi.\r\nNew England\'daki seçkin, eski moda bir yatılı okulda, tutkulu bir İngilizce öğretmeni, öğrencilerine geleneklere başkaldırmaları ve her günün potansiyelini yakalamaları için ilham verirken, sert müdürün küçümsemesine neden olur.\r\n', NULL),
(33, 'Django Unchained', 'Quentin Tarantino', 2012, 'Western', 'afisler/52516-django-unchained-0-1000-0-1500-crop.jpg', '2024-10-25 07:47:38', 'Hayat, özgürlük ve intikam arayışı.\r\nAzat edilmiş bir köle, Alman bir ödül avcısının yardımıyla karısını acımasız Mississippi plantasyon sahibinden kurtarmak için yola çıkar.', NULL),
(34, 'Shutter Island', 'Martin Scorsese', 2010, 'Gizem', 'afisler/45409-shutter-island-0-1000-0-1500-crop.jpg', '2024-10-25 07:52:04', 'Bazı yerler gitmenize asla izin vermez.\r\nİkinci Dünya Savaşı askeriyken ABD\'li bir polis memuru olan Teddy Daniels, bir akıl hastanesindeki bir hastanın kayboluşunu araştırır, ancak çabaları rahatsız edici hayaller ve gizemli bir doktor tarafından tehlikeye atılır.', NULL),
(35, 'Inglourious Basterds', 'Quentin Tarantino', 2009, 'Savaş', 'afisler/41352-inglourious-basterds-0-1000-0-1500-crop.jpg', '2024-10-25 07:55:13', 'Bir Basterd\'ın işi asla bitmez.\r\nİkinci Dünya Savaşı sırasında Nazi işgali altındaki Fransa\'da, “Basterds” olarak bilinen bir grup Yahudi-Amerikan askeri, Nazilerin kafa derilerini yüzerek ve vahşice öldürerek Üçüncü Reich\'a korku salmak için özel olarak seçilir. Teğmen Aldo Raine liderliğindeki Basterds\'ın yolu çok geçmeden Paris\'te bir sinema salonu işleten ve askerler tarafından hedef alınan Fransız-Yahudi bir genç kızla kesişir.', NULL),
(37, 'Eyes Wide Shut', 'Stanley Kubrick', 1999, 'Gerilim', 'afisler/51717-eyes-wide-shut-0-1000-0-1500-crop.jpg', '2024-10-25 07:59:54', 'Cruise. Kidman. Kubrick.\r\nDr. Bill Harford\'un karısı Alice, tanıştığı bir adam hakkında cinsel fantezileri olduğunu itiraf ettikten sonra, Bill cinsel ilişkiye girmeyi takıntı haline getirir. Bir yeraltı cinsel grubunu keşfeder ve toplantılarından birine katılır - ve kısa sürede boyundan büyük işlere kalkıştığını keşfeder.', NULL),
(38, 'Fallen Angels', 'Wong Kar-wai', 1995, 'Romantik', 'afisler/45489-fallen-angels-0-1000-0-1500-crop.jpg', '2024-10-25 08:02:06', 'Gece tuhaflıklarla dolu.\r\nBir suikastçı, kendisine gizliden gizliye ilgi duyan ortağının karşı çıkmasına rağmen şiddet dolu yaşam tarzından kaçmaya çalışırken engellerle karşılaşır.', NULL),
(39, 'Mad Max: Fury Road', 'George Miller', 2015, 'Bilim Kurgu', 'afisler/62780-mad-max-fury-road-0-1000-0-1500-crop.jpg', '2024-11-17 18:02:52', 'Gelecek delilere aittir.\r\nGezegenimizin en uzak köşelerinde, insanlığın çöktüğü ve herkesin yaşamın gereklilikleri için çılgınca savaştığı keskin bir çöl manzarasında geçen bir kıyamet hikayesi. Bu dünyada, düzeni yeniden sağlayabilecek iki asi kaçak olarak yaşamaktadır.', NULL),
(40, 'Gladiator', 'Ridley Scott', 2000, 'Savaş', 'afisler/51952-gladiator-2000-0-1000-0-1500-crop.jpg', '2024-11-19 06:17:06', 'Hayatta yaptıklarımız sonsuzlukta yankılanır.\r\n180 yılında imparator Marcus Aurelius\'un ölümü Roma İmparatorluğu\'nu kaosa sürükler. Maximus, Roma ordusunun en yetenekli ve güvenilir generallerinden biridir ve imparatorun önemli bir danışmanıdır. Marcus\'un sinsi oğlu Commodus tahta çıkarken, Maximus idam edilecektir. Kaçar ama köle tüccarları tarafından yakalanır. İspanyol adını alan ve gladyatör olmaya zorlanan Maximus, para ödeyen seyircileri eğlendirmek için diğer erkeklerle ölümüne dövüşmek zorundadır.', NULL),
(41, 'Good Will Hunting', 'Gus Van Sant', 1997, 'Dram', 'afisler/51621-good-will-hunting-0-1000-0-1500-crop.jpg', '2024-11-19 06:19:11', 'Bazı insanlar kendilerine asla inanamazlar, ta ki biri onlara inanana kadar.\r\nProfesörler, amaçsız bir hademenin aynı zamanda bir matematik dehası olduğunu keşfettiğinde, bir terapist genç adamın kendisini geride tutan şeytanlarla yüzleşmesine yardımcı olur.', NULL),
(42, 'Black Swan', 'Darren Aronofsky', 2010, 'Dram', 'afisler/bIjkE9Og0nulRycj144sCcQcsZ6-0-1000-0-1500-crop.jpg', '2024-11-19 06:21:30', 'Mükemmellik sadece kontrolle ilgili değildir. Aynı zamanda kendini bırakmakla da ilgilidir.\r\nNew York\'taki bir bale topluluğunda balerin olan Nina\'nın hikâyesi, kendi mesleğindeki herkes gibi hayatını tamamen dansa adamıştır. Nina, kızının mesleki hırsını gayretle destekleyen emekli balerin annesi Erica ile birlikte yaşamaktadır. Sanat yönetmeni Thomas Leroy, yeni sezonun açılış gösterisi Kuğu Gölü için baş balerin Beth MacIntyre\'ı değiştirmeye karar verdiğinde, Nina onun ilk tercihidir.', NULL),
(43, '(500) Days of Summer', 'Marc Webb', 2009, 'Romantik', 'afisler/39350--500-days-of-summer-0-1000-0-1500-crop.jpg', '2024-11-19 06:22:43', 'Bu bir aşk hikayesi değil. Bu aşk hakkında bir hikâye.\r\nTebrik kartı yazarı ve umutsuz bir romantik olan Tom, kız arkadaşı Summer onu aniden terk edince tamamen hazırlıksız yakalanır. Birlikte geçirdikleri 500 günü düşünerek aşk ilişkilerinin nerede bozulduğunu anlamaya çalışır ve bunu yaparken Tom hayattaki gerçek tutkularını yeniden keşfeder.', NULL),
(44, 'Scott Pilgrim vs. the World', 'Edgar Wright', 2010, 'Dram', 'afisler/2B5zjs5E3xerqAyowpw3QcOCyLq-0-1000-0-1500-crop.jpg', '2024-11-19 06:23:49', 'Destansı bir epiklik destanı.\r\nBir garaj-rock grubunun bas gitaristi olan Scott Pilgrim, kız arkadaş edinmekte hiç zorlanmamıştır; genellikle sorun onlardan kurtulmaktır. Ancak Ramona Flowers kalbine girdiğinde, onun en belalı yüke sahip olduğunu fark eder: onu talipler listesinden çıkarmak için hiçbir şeyden kaçınmayacak eski erkek arkadaşlardan oluşan bir ordu.', NULL),
(45, 'The Lord of the Rings: The Fellowship of the Ring', 'Peter Jackson', 2001, 'Fantastik', 'afisler/1tX9ZlgVvWjAQhMs1vAfsYpi7VK-0-1000-0-1500-crop.jpg', '2024-11-19 06:24:59', 'Hepsine hükmedecek bir yüzük.\r\nAmcası Bilbo\'dan gizemli bir yüzük miras alan genç hobbit Frodo Baggins, yüzüğün kötü yaratıcısının eline geçmesini engellemek için evinden ayrılmak zorunda kalır. Yol boyunca, yüzük taşıyıcısını korumak ve yüzüğün nihai hedefine ulaştığından emin olmak için bir yoldaşlık kurulur: Yok edilebileceği tek yer olan Kıyamet Dağı\'na.', NULL),
(46, 'The Lord of the Rings: The Two Towers', 'Peter Jackson', 2002, 'Fantastik', 'afisler/51929-the-lord-of-the-rings-the-two-towers-0-1000-0-1500-crop.jpg', '2024-11-19 06:25:48', 'Kardeşlik bozuldu. Karanlığın gücü artıyor...\r\nFrodo Baggins ve Yoldaşlık\'ın diğer üyeleri Tek Yüzük\'ü yok etmek için kutsal görevlerine devam ediyorlar ama ayrı yollardan. Kaderleri, yozlaşmış büyücü Saruman\'ın beklediği Isengard\'daki Orthanc Kulesi ve Mordor\'un karanlık topraklarının derinliklerindeki Barad-dur\'daki Sauron\'un kalesi olmak üzere iki kulede yatmaktadır. Frodo ve Sam, Tek Güç Yüzüğü\'nü yok etmek için Mordor\'a doğru yürürken, Gimli, Legolas ve Aragorn da orkların esir aldığı Merry ve Pippin\'i aramaktadır. Tüm bunlar olurken hain büyücü Saruman, Yoldaşlık üyelerini Isengard\'daki Orthanc Kulesi\'nde beklemektedir.', NULL),
(47, 'The Lord of the Rings: The Return of the King', 'Peter Jackson', 2003, 'Fantastik', 'afisler/xieWkPAgQrrk5wOyncayPd65hrp-0-1000-0-1500-crop.jpg', '2024-11-19 06:26:33', 'Kayıp olmadan zafer olmaz. Acı çekmeden zafer olmaz. Fedakârlık olmadan özgürlük olmaz.\r\nOrdular dünyanın kaderini belirleyecek son bir savaş için toplanırken ve Aydınlık ile Karanlık\'ın güçlü, kadim güçleri sonucu belirlemek için yarışırken, Yüzük Kardeşliği\'nin bir üyesinin İnsanların Kralları\'nın tahtının asil varisi olduğu ortaya çıkar. Yine de kötülüğe karşı zafer kazanmanın tek umudu, sadık dostu Sam ve iğrenç, sefil Gollum\'un eşliğinde, Güç Yüzüğü\'nü yok etmek için imkansız görünen arayışında Mordor\'un karanlık kalbinin derinliklerine inen cesur bir hobbit olan Frodo\'da yatmaktadır.', NULL),
(48, 'Titanic', 'James Cameron', 1997, 'Dram', 'afisler/51524-titanic-0-1000-0-1500-crop.jpg', '2024-11-19 06:27:38', 'Dünya üzerinde hiçbir şey onların arasına giremezdi.\r\n101 yaşındaki Rose DeWitt Bukater, 84 yıl sonra Titanik\'teki yaşamının öyküsünü anlatıyor. Genç Rose, annesi ve nişanlısıyla birlikte gemiye biner. Bu arada Jack Dawson ve Fabrizio De Rossi gemide üçüncü sınıf bilet kazanırlar. Rose, Titanik\'in yola çıkışından 15 Nisan 1912\'deki ilk ve son seferinde ölümüne kadar olan tüm hikâyeyi anlatıyor.', NULL),
(49, 'Star Wars', 'George Lucas', 1977, 'Fantastik', 'afisler/2706-star-wars-0-1000-0-1500-crop.jpg', '2024-11-19 06:28:45', 'Uzun zaman önce, çok çok uzak bir galakside.\r\nPrenses Leia, galaktik İmparatorluğu ele geçirmeye çalışan kötü İmparatorluk güçleri tarafından yakalanır ve rehin tutulur. Cesur Luke Skywalker ve atılgan kaptan Han Solo, güzel prensesi kurtarmak ve İmparatorluk\'ta barış ve adaleti yeniden tesis etmek için sevimli robot ikilisi R2-D2 ve C-3PO ile bir araya gelir.', NULL),
(50, 'The Empire Strikes Back', 'Irvin Kershner', 1980, 'Fantastik', 'afisler/7BuH8itoSrLExs2YZSsM01Qk2no-0-1000-0-1500-crop.jpg', '2024-11-19 06:29:36', 'Yıldız Savaşları efsanesi devam ediyor.\r\nDestan, Luke Skywalker\'ın kötü Galaktik İmparatorluğu yenme umuduyla yaşlı usta Yoda\'dan Jedi yöntemlerini öğrenmesiyle devam ediyor. Ancak Darth Vader, Luke\'u yakalamak için her zamankinden daha kararlıdır. Bu arada, asi lider Prenses Leia, ukala Han Solo, Chewbacca ve droidler C-3PO ve R2-D2 çeşitli yakalanma, ihanet ve umutsuzluk aşamalarına atılırlar.', NULL),
(51, 'Return of the Jedi', 'Richard Marquand', 1983, 'Fantastik', 'afisler/5wDrNqePjb5SOucrWQwiFu340vv-0-1000-0-1500-crop.jpg', '2024-11-19 06:30:08', 'Çok çok uzak bir galaksiye geri dönün.\r\nLuke Skywalker, arkadaşı Han Solo\'yu Jabba the Hutt\'ın pençelerinden kurtarmak için bir göreve liderlik ederken, İmparator ikinci bir korkunç Ölüm Yıldızı ile İsyancıları sonsuza dek yok etmeye çalışıyor.', NULL),
(52, 'Star Wars: Episode I – The Phantom Menace', 'George Lucas', 1999, 'Fantastik', 'afisler/50711-star-wars-episode-i-the-phantom-menace-0-1000-0-1500-crop.jpg', '2024-11-19 06:30:50', 'Her neslin bir efsanesi vardır. Her yolculuğun bir ilk adımı vardır. Her destanın bir başlangıcı vardır.\r\nGüç\'e sahip genç bir köle olan Anakin Skywalker, Tatooine\'de keşfedilir. Bu sırada kötü Sith\'ler geri dönmüş, Jedi\'lardan intikam almak için planlarını uygulamaya koymuşlardır.', NULL),
(53, 'Star Wars: Episode II – Attack of the Clones', 'George Lucas', 2002, 'Fantastik', 'afisler/50710-star-wars-episode-ii-attack-of-the-clones-0-1000-0-1500-crop.jpg', '2024-11-19 06:31:47', 'Bir Jedi öfke nedir bilmemeli. Ne de nefreti. Ne de sevgi.\r\nSenatör Padmé Amidala\'ya düzenlenen bir suikast girişiminin ardından Jedi Şövalyeleri Anakin Skywalker ve Obi-Wan Kenobi, galaksiyi sonsuza dek değiştirebilecek gizemli bir komployu araştırır.', NULL),
(54, 'Star Wars: Episode III – Revenge of the Sith', 'George Lucas', 2005, 'Fantastik', 'afisler/50709-star-wars-episode-iii-revenge-of-the-sith-0-1000-0-1500-crop.jpg', '2024-11-19 06:32:31', 'Destan tamamlandı.\r\nŞeytani Darth Sidious sınırsız güç için son planını yürürlüğe koyuyor - ve kahraman Jedi Anakin Skywalker bir taraf seçmek zorunda.', NULL),
(55, 'Drive', 'Nicolas Winding Refn', 2011, 'Dram', 'afisler/nu7XIa67cXc2t7frXCE5voXUJcN.jpg-0-1000-0-1500-crop.jpg', '2024-11-19 06:33:28', 'Temiz kaçış yoktur.\r\nDriver, suçlular için ek iş olarak kaçış şoförlüğü yapan yetenekli bir Hollywood dublörüdür. Buz gibi bir dış görünüşü olmasına rağmen, son zamanlarda Irene adında güzel bir komşuya ve onun küçük oğlu Benicio\'ya ısınmaktadır. Irene\'nin kocası hapisten çıkınca, bir milyon dolarlık bir soygun için Driver\'dan yardım ister. İş korkunç bir şekilde ters gider ve Driver, Irene ile Benicio\'yu soygunun arkasındaki intikamcı beyinden korumak için hayatını riske atmak zorunda kalır.', NULL),
(56, 'Little Miss Sunshine', 'Jonathan Dayton, Valerie Faris', 2006, 'Dram', 'afisler/dOeM4R55TsAFBXCPNIDDMiJkePr-0-1000-0-1500-crop.jpg', '2024-11-19 06:34:04', 'Çöküşün eşiğinde bir aile\r\nİlginç ve renkli karakterlerle dolu bir aile, eski bir minibüse doluşur ve küçük Olive\'in güzellik yarışmasına katılması için Kaliforniya\'ya doğru yola çıkar.', NULL),
(57, 'Up', 'Pete Docter', 2009, 'Animasyon', 'afisler/43302-up-0-1000-0-1500-crop.jpg', '2024-11-19 06:35:21', 'En büyük macera eve dönmektir.\r\nCarl Fredricksen tüm hayatını dünyayı keşfetmeyi ve hayatı dolu dolu yaşamayı hayal ederek geçirmiştir. Ancak 78 yaşındayken, kaderin bir cilvesi (ve Russell adında 8 yaşındaki inatçı bir Vahşi Doğa Kaşifi) ona hayatında yeni bir sayfa açana kadar hayat onu geçip gitmiş gibi görünüyor.', NULL),
(58, 'Aftersun', 'Charlotte Wells', 2022, 'Dram', 'afisler/868558-aftersun-0-1000-0-1500-crop.jpg', '2024-11-19 06:36:21', 'Hafıza acı verir.\r\nSophie, yirmi yıl önce babasıyla çıktığı bir tatilin ortak sevincini ve özel melankolisini düşünür. Tanıdığı baba ile tanımadığı adamı uzlaştırmaya çalışırken, gerçek ve hayali anılar miniDV görüntülerin arasındaki boşlukları doldurur.\r\n', NULL),
(59, 'Prisoners', 'Denis Villeneuve', 2013, 'Dram', 'afisler/3w79tTsv6tmlT8Jww6snyPrgVok-0-1000-0-1500-crop.jpg', '2024-11-19 06:37:04', 'Her an önemlidir.\r\nKeller Dover her ebeveynin en kötü kabusuyla karşı karşıyadır. Altı yaşındaki kızı Anna, genç arkadaşı Joy ile birlikte kayıptır ve dakikalar saatlere dönüşürken panik başlar. Ellerindeki tek ipucu, daha önce sokaklarına park edilmiş olan harap bir karavandır.', NULL),
(60, '2001: A Space Odyssey', 'Stanley Kubrick', 1968, 'Bilim Kurgu', 'afisler/eDiexVN4nO3ZdDZCDMiJOX5fQ5r-0-1000-0-1500-crop.jpg', '2024-11-19 06:37:57', 'Nihai yolculuk.\r\nİnsanlık, ay yüzeyinin altına gömülmüş gizemli bir nesne bulur ve dünyanın en gelişmiş süper bilgisayarı HAL 9000\'in yardımıyla bu nesnenin kökenini bulmak için yola çıkar.', NULL),
(61, 'Memento', 'Christopher Nolan', 2000, 'Gizem', 'afisler/memento-0-1000-0-1500-crop.jpg', '2024-11-19 06:44:48', 'Bazı anıları unutmak en iyisidir.\r\nLeonard Shelby, karısına tecavüz edip öldüren adamın izini sürmektedir. Ancak karısının katilini bulmanın zorluğu, nadir görülen ve tedavi edilemeyen bir tür kısa süreli hafıza kaybından muzdarip olmasıyla daha da artar. Kazadan önceki hayatının ayrıntılarını hatırlayabilmesine rağmen Leonard, on beş dakika önce ne olduğunu, nereye gittiğini ya da nedenini hatırlayamamaktadır.', NULL),
(62, 'Alien', 'Ridley Scott', 1979, 'Korku', 'afisler/bg7K6VtUG7Ew70gQj6SSroD5d4R-0-1000-0-1500-crop.jpg', '2024-11-19 06:47:26', 'Uzayda kimse çığlıklarınızı duyamaz.\r\nTicari uzay gemisi Nostromo, dünyaya dönüşü sırasında uzak bir gezegenden gelen bir yardım sinyali yakalar. Mürettebattan üç kişilik bir ekip gezegende binlerce yumurta içeren bir oda keşfettiğinde, yumurtalardan birinin içindeki bir yaratık bir kaşife saldırır. Talihsiz ev sahibinin içine yerleştirilen uzaylı parazit doğduğunda, tüm mürettebat üzerlerine çökecek olan kâbustan habersizdir.', NULL),
(63, 'GoodFellas', 'Martin Scorsese', 1990, 'Suç', 'afisler/51383-goodfellas-0-1000-0-1500-crop (1).jpg', '2024-11-19 06:49:07', 'Mafya hayatının otuz yılı.\r\nYarı İrlandalı, yarı Sicilyalı Brooklynli bir çocuk olan Henry Hill\'in küçük yaşta mahalle gangsterleri tarafından evlat edinilmesi ve Jimmy Conway\'in rehberliğinde bir mafya ailesinin basamaklarını tırmanmasının gerçek hikayesi.', NULL),
(64, 'Catch Me If You Can', 'Steven Spielberg', 2002, 'Suç', 'afisler/51484-catch-me-if-you-can-0-1000-0-1500-crop.jpg', '2024-11-19 06:49:50', 'Gerçek bir sahtekârın gerçek hikâyesi.\r\nFrank Abagnale Jr. hakkında gerçek bir hikâye. 19 yaşına gelmeden önce Pan Am pilotu, doktor ve hukuk savcısı olarak milyonlarca dolarlık çekleri dolandırmayı başarmıştır. Bir FBI ajanı onu parmaklıklar ardına koymayı kendine görev edinir. Ancak Frank sadece yakalanmaktan kaçmakla kalmaz, takip edilmekten de zevk alır.', NULL),
(65, 'WALL·E', 'Andrew Stanton', 2008, 'Animasyon', 'afisler/45994-walle-0-1000-0-1500-crop.jpg', '2024-11-19 06:53:57', '700 yıl boyunca ne için yapıldığını yaptıktan sonra, ne için yaratıldığını keşfedecek.\r\nYa insanoğlu Dünya\'yı terk etmek zorunda kalsaydı ve biri son robotu kapatmayı unutsaydı? Yüzlerce yıl boyunca ne için yaratıldıysa onu yapan WALL-E, EVE adında şık bir arama robotuyla tanıştığında hayatında yeni bir amaç keşfeder. EVE, WALL-E\'nin yanlışlıkla gezegenin geleceğinin anahtarına rastladığını fark eder ve insanlara rapor vermek için uzaya geri döner. Bu arada, WALL-E EVE\'i galaksi boyunca kovalar ve şimdiye kadar beyaz perdeye aktarılan en yaratıcı maceralardan birini başlatır.', NULL),
(66, 'Nightcrawler', 'Dan Gilroy', 2014, 'Gerilim', 'afisler/A9ANrAWlmIovxzjAIiOgseSLNc9-0-1000-0-1500-crop.jpg', '2024-11-19 06:54:53', 'Şehir en çok geceleri ışıldar\r\nLou Bloom, iş bulma umuduyla Los Angeles\'ın suç gazeteciliği dünyasına girdiğinde, kendi hikâyesinin yıldızı olmak için gözlemci ve katılımcı arasındaki çizgiyi bulanıklaştırır. Bu çabasında ona yardımcı olan kişi ise televizyon haberciliğinde deneyimli Nina\'dır.', NULL),
(67, 'Howl’s Moving Castle', 'Hayao Miyazaki', 2004, 'Animasyon', 'afisler/49062-howl-s-moving-castle-0-1000-0-1500-crop.jpg', '2024-11-19 06:55:46', 'İkisi orada yaşıyordu.\r\nGenç bir değirmenci olan Sophie, dükkânına giren ve onu lanetleyen bir cadı tarafından yaşlı bir kadına dönüştürülür. Howl adında bir büyücüyle karşılaşır ve onun kral için savaşmaya karşı direnişine kapılır.', NULL),
(68, 'Spider-Man', 'Sam Raimi', 2002, 'Fantastik', 'afisler/51561-spider-man-0-1000-0-1500-crop.jpg', '2024-11-19 06:56:26', 'Nihai dönüş için gidin.\r\nOscorp\'ta genetiği değiştirilmiş bir örümcek tarafından ısırıldıktan sonra, inek ama sevimli lise öğrencisi Peter Parker, Örümcek Adam olarak bilinen süper kahraman olmak için inanılmaz güçlerle donatılır.\r\n', NULL),
(69, 'Spider-Man 2', 'Sam Raimi', 2004, 'Fantastik', 'afisler/7JtMVM58MnzxWeyubzLpXBiVnDC-0-1000-0-1500-crop.jpg', '2024-11-19 06:57:04', 'Hepimizin içinde bir kahraman var.\r\nPeter Parker büyük bir kimlik krizi yaşamaktadır. Örümcek Adam olmaktan yorulduğu için süper kahraman alter egosunu rafa kaldırmaya karar verir ve bu da şehri kötü Doc Ock\'un bıraktığı katliamın ardından acı içinde bırakır. Bu arada Parker, çocukluğundan beri sevdiği Mary Jane Watson\'a olan duygularını hâlâ harekete geçirememiştir. En yakın arkadaşı Harry Osborn\'un da içinde bir öfke oluşmaya başlar...', NULL),
(70, 'Spider-Man 3', 'Sam Raimi', 2007, 'Fantastik', 'afisler/uC2pAMjb32NIgQ1GdC1Bl6LZJc2-0-1000-0-1500-crop.jpg', '2024-11-19 06:57:39', 'En büyük savaş içeride yatıyor.\r\nGörünüşte yenilmez olan Örümcek Adam, şekil değiştiren Kum Adam da dahil olmak üzere yepyeni bir kötü adam grubuyla karşı karşıya geliyor. Örümcek Adam\'ın süper güçleri uzaylı bir organizma tarafından değiştirilirken, alter egosu Peter Parker, düşmanı Eddie Brock ile uğraşır ve aynı zamanda bir aşk üçgenine yakalanır.', NULL),
(71, 'Avatar', 'James Cameron', 2009, 'Fantastik', 'afisler/b7nR3eKeTOwHPKmDLUWunIGasKo-0-1000-0-1500-crop.jpg', '2024-11-19 06:58:26', 'Pandora\'nın dünyasına girin.\r\n22. yüzyılda, felçli bir deniz piyadesi benzersiz bir görev için Pandora uydusuna gönderilir, ancak emirlere uymakla uzaylı bir uygarlığı korumak arasında kalır.', NULL),
(72, 'Requiem for a Dream', 'Darren Aronofsky', 2000, 'Gerilim', 'afisler/muym4jTjdLx7E6as09d1wlC3sOB-0-1000-0-1500-crop.jpg', '2024-11-19 06:59:39', 'Dört Coney Adası sakininin uyuşturucuya bağlı ütopyaları, bağımlılıkları derinlere indiğinde paramparça olur.', NULL),
(73, 'A Quiet Place', 'John Krasinski', 2018, 'Korku', 'afisler/379687-a-quiet-place-0-1000-0-1500-crop.jpg', '2024-11-19 07:01:30', 'Sizi duyarlarsa, avlarlar.\r\nBir aile, sesle avlanan yaratıklardan saklanırken sessizlik içinde yaşamak zorunda kalır.', NULL),
(74, 'Home Alone', 'Chris Columbus', 1990, 'Aile', 'afisler/8IWPBT1rkAaI8Kpk5V3WfQRklJ7-0-1000-0-1500-crop.jpg', '2024-11-19 07:03:00', 'Ailesiz bir aile komedisi.\r\nSekiz yaşındaki Kevin McCallister, ailesi Noel tatiline giderken farkında olmadan onu geride bırakınca durumdan en iyi şekilde yararlanır. Ancak bir çift beceriksiz hırsız Kevin\'in evine göz diktiğinde, cesur çocuk kendi bölgesini savunmaya hazırdır. Çılgına dönen annesi Noel gününden önce eve dönmeye çalışırken, sevimli yaramaz Kevin bol bol bubi tuzağı kurarak yerini korur.', NULL),
(75, 'It', 'Andy Muschietti', 2017, 'Korku', 'afisler/6uDpMsdn8bbZScDptbika5JEtSH-0-1000-0-1500-crop.jpg', '2024-11-28 07:13:41', 'Siz de yüzeceksiniz.\r\nMaine\'deki küçük bir kasabada, Kaybedenler Kulübü olarak bilinen yedi çocuk, yaşam sorunları, zorbalar ve Pennywise adında bir palyaço şeklini alan bir canavarla yüz yüze gelir.', NULL),
(76, 'A Clockwork Orange', 'Stanley Kubrick', 1971, 'Suç', 'afisler/51867-a-clockwork-orange-0-1000-0-1500-crop.jpg', '2024-11-28 07:16:27', 'Başlıca ilgi alanları tecavüz, aşırı şiddet ve Beethoven olan genç bir adamın maceraları.\r\nYakın gelecekteki İngiltere\'de, genç Alexander DeLarge ve arkadaşları istedikleri herkesi döverek ve tecavüz ederek eğlenmektedirler. Alex, başkalarının hayatlarını mahvetmediği zamanlarda Beethoven\'ın müziği eşliğinde kendinden geçmektedir. Çocuk suçlarını azaltmaya hevesli olan devlet, hapisteki Alex\'e, tüm kişisel eylemlerini elinden alacak invaziv bir prosedürden geçme seçeneği sunar. Vicdanın bir meta olduğu bir zamanda, Alex fikrini değiştirebilecek midir?', NULL),
(77, 'Before Sunrise', 'Richard Linklater', 1995, 'Romantik', 'afisler/51974-before-sunrise-0-1000-0-1500-crop.jpg', '2024-11-28 07:17:35', 'Hayatınızın en büyük aşkı sadece bir gece sürebilir mi?\r\nGenç bir adam ve kadın Avrupa\'da bir trende tanışır ve Viyana\'da bir geceyi birlikte geçirirler. Ne yazık ki ikisi de bunun muhtemelen birlikte geçirecekleri tek gece olacağını bilmektedir.', NULL),
(78, 'Batman Begins', 'Christopher Nolan', 2005, 'Fantastik', 'afisler/51784-batman-begins-0-1000-0-1500-crop.jpg', '2024-11-28 07:19:13', 'Kötülük şövalyeden korkar.\r\nTrajedinin sürüklediği milyarder Bruce Wayne, hayatını evi Gotham Şehri\'nin başına bela olan yozlaşmayı ortaya çıkarmaya ve yenmeye adar. Sistem içinde çalışamayan Wayne, bunun yerine yeraltı suç dünyası için bir korku sembolü olan yeni bir kimlik yaratır: Batman.', NULL),
(79, 'The Dark Knight Rises', 'Christopher Nolan', 2012, 'Fantastik', 'afisler/16550-the-dark-knight-rises-0-1000-0-1500-crop.jpg', '2024-11-28 07:20:08', 'Bir ateş yükselecek.\r\nBölge Savcısı Harvey Dent\'in ölümünün ardından Batman, merhum avukatın itibarını korumak için Dent\'in suçlarının sorumluluğunu üstlenir ve ardından Gotham Şehri Polis Departmanı tarafından aranmaya başlar. Sekiz yıl sonra Batman, gizemli Selina Kyle ve Gotham\'ın en iyilerini alt eden yeni bir terörist lider olan kötü Bane ile karşılaşır. Kara Şövalye, kendisini düşman ilan eden şehri korumak için yeniden ortaya çıkar.', NULL),
(80, 'John Wick', 'Chad Stahelski', 2014, 'Suç', 'afisler/172076-john-wick-0-1000-0-1500-crop.jpg', '2024-11-28 07:21:19', 'Onu kızdırmayın.\r\nEski tetikçi John Wick, her şeyini elinden alan gangsterlerin izini sürmek için emeklilikten ayrılır.', NULL),
(81, 'John Wick: Chapter 2', 'Chad Stahelski', 2017, 'Suç', 'afisler/fWz9LMfdES80BsJKucgzI5ZJhnB-0-1000-0-1500-crop.jpg', '2024-11-28 07:22:16', 'Asla şeytanı arkadan bıçaklamayın!\r\nJohn Wick, karanlık bir uluslararası suikastçılar loncasının kontrolünü ele geçirmek isteyen eski bir ortağı tarafından emekliliğe zorlanır. Ona yardım etmek için kan yemini eden Wick, Roma\'ya gider ve dünyanın en tehlikeli katillerinden bazılarına karşı savaşır.', NULL),
(82, 'John Wick: Chapter 3 – Parabellum', 'Chad Stahelski', 2019, 'Suç', 'afisler/390039-john-wick-chapter-3-parabellum-0-1000-0-1500-crop.jpg', '2024-11-28 07:22:58', 'Barış istiyorsanız, savaşa hazırlanın.\r\nSüper suikastçı John Wick, başında 14 milyon dolarlık bir ödül etiketi ve peşinde ödül avcısı katillerden oluşan bir orduyla geri dönüyor. Karanlık uluslararası suikastçı loncası Yüksek Masa\'nın bir üyesini öldürdükten sonra John Wick aforoz edilir, ancak dünyanın en acımasız kiralık katil kadın ve erkekleri onun her adımını beklemektedir.', NULL),
(83, 'Shrek', 'Andrew Adamson, Vicky Jenson', 2001, 'Animasyon', 'afisler/51344-shrek-0-1000-0-1500-crop.jpg', '2024-11-28 07:24:32', 'Hiç anlatılmamış en büyük peri masalı.\r\nYeşil olmak kolay değil - özellikle de Shrek adında sevimli (kokuşmuş da olsa) bir devseniz. Muhteşem bir prensesi ateş püskürten bir ejderhanın pençelerinden kurtarmak için göreve çıkan Shrek, beklenmedik bir yoldaşla, esprili bir eşekle işbirliği yapar.', NULL),
(84, 'Amélie', 'Jean-Pierre Jeunet', 2001, 'Dram', 'afisler/pM20xF4WFyX7G3ie0YBXFp75aEC-0-1000-0-1500-crop.jpg', '2024-11-28 07:35:51', 'Hayatınızı değiştirecek.\r\nParis\'teki küçük bir kafede, sevimli ama acı verici derecede utangaç Amélie kazara başkalarına yardım etme yeteneğini keşfeder. Çok geçmeden Amelie günlerini bir çöpçatan, koruyucu melek ve her yönüyle iyiliksever olarak geçirmeye başlar. Ama yakışıklı bir yabancıyla karşılaştığında, kendi aşk hikâyesinin yıldızı olacak cesareti bulabilecek midir?', NULL),
(85, 'John Wick: Chapter 4', 'Chad Stahelski', 2023, 'Suç', 'afisler/530882-john-wick-chapter-4-0-1000-0-1500-crop.jpg', '2024-11-30 13:38:31', 'Geri dönüş yok, tek çıkış yolu var.\r\nBaşına konan ödül giderek artarken John Wick, Yüksek Masa\'yı yenmenin bir yolunu keşfeder. Ancak özgürlüğünü kazanmadan önce Wick, dünya çapında güçlü ittifaklara ve eski dostları düşmana dönüştüren güçlere sahip yeni bir düşmanla yüzleşmek zorundadır.', NULL),
(86, 'Top Gun', 'Tony Scott', 1986, 'Aksiyon', 'afisler/fKSZl8ONN7DQh5ujgdObRIFmhiZ-0-1000-0-1500-crop.jpg', '2025-01-01 12:22:33', 'En iyilerin en iyileriyle birlikte.\r\nTeğmen Pete \'Maverick\' Mitchell ile arkadaşı ve yardımcı pilotu Nick \'Goose\' Bradshaw için, savaş pilotları için seçkin bir eğitim okuluna kabul edilmek bir hayalin gerçekleşmesidir. Ancak bir trajedi ve kişisel şeytanlar, Pete\'in as pilot olma hayallerini tehdit edecektir.', NULL),
(87, 'Top Gun: Maverick', 'Joseph Kosinski', 2022, 'Aksiyon', 'afisler/293465-top-gun-maverick-0-1000-0-1500-crop.jpg', '2025-01-01 12:23:34', 'İhtiyacı hissedin... Hız ihtiyacını.\r\nPete “Maverick” Mitchell, Donanma\'nın en iyi havacılarından biri olarak otuz yıldan fazla hizmet verdikten ve kendisini yere indirecek rütbe ilerlemesinden kaçındıktan sonra, kendisini yaşayan hiçbir pilotun görmediği özel bir görev için TOP GUN mezunlarından oluşan bir müfrezeyi eğitirken bulur.', NULL),
(88, 'Léon: The Professional', 'Luc Besson', 1994, 'Aksiyon', 'afisler/gE8S02QUOhVnAmYu4tcrBlMTujz-0-1000-0-1500-crop.jpg', '2025-01-01 12:24:40', 'İşin doğru yapılmasını istiyorsanız, bir profesyonel tutun.\r\nNew York\'un en iyi tetikçisi olan Léon, etkili bir “temizlikçi” olarak ün kazanmıştır. Ancak kapı komşuları serseri bir DEA ajanı tarafından ortadan kaldırılınca, 12 yaşındaki Mathilda\'nın isteksiz vasisi olur. Çok geçmeden Mathilda\'nın düşünceleri intikama dönüşür ve Léon\'un ayak izlerini takip etmeyi düşünür.', NULL),
(89, 'Kill Bill: Vol. 1', 'Quentin Tarantino', 2003, 'Aksiyon', 'afisler/9O50TVszkz0dcP5g6Ej33UhR7vw-0-1000-0-1500-crop.jpg', '2025-01-01 12:25:27', 'Kükreyen bir intikam ateşi.\r\nBir suikastçı, acımasız patronu Bill ve suikast çemberinin diğer üyeleri tarafından vurulur ama intikamını planlamak için yaşar.', NULL),
(90, 'Kill Bill: Vol. 2', 'Quentin Tarantino', 2004, 'Aksiyon', 'afisler/bxbX4sHZHcy81dnNs4VAVs7HXDL-0-1000-0-1500-crop.jpg', '2025-01-01 12:25:56', 'Gelin son kurgu için geri döndü.\r\nGelin, kendisini ve doğmamış çocuğunu öldürmeye çalışan suikastçılar çetesine karşı intikam hırsıyla kükremeye devam ediyor. Bill\'i öldürmekten başka yapacak bir şeyi kalmayana kadar, eski ortaklarının her birini tek tek ziyaret ederek Ölüm Listesi Beş\'teki kurbanları kontrol ediyor.', NULL),
(91, 'Superbad', 'Greg Mottola', 2007, 'Komedi', 'afisler/47776-superbad-0-1000-0-1500-crop.jpg', '2025-01-01 12:27:26', 'Gelin ve biraz alın!\r\nBirbirine bağımlı iki lise son sınıf öğrencisi, içkili bir parti düzenleme planları ters gidince ayrılık kaygısıyla baş etmek zorunda kalır.', NULL),
(92, 'The Nice Guys', 'Shane Black', 2016, '2016', 'afisler/216301-the-nice-guys-0-1000-0-1500-crop.jpg', '2025-01-01 12:27:56', 'O kadar da iyi değiller.\r\nÖzel bir dedektif, 1970\'lerin Los Angeles\'ında yıldızı sönmekte olan bir porno yıldızının intiharını araştırır ve bir komployu ortaya çıkarır.', NULL),
(93, 'The Hangover', 'Todd Phillips', 2009, 'Komedi', 'afisler/40100-the-hangover-0-1000-0-1500-crop.jpg', '2025-01-01 12:28:26', 'Bazı erkekler Vegas\'la başa çıkamaz.\r\nÜç arkadaş, bekârlığa veda partisi eğlenceleriyle geçen gürültülü bir gecenin ardından nihayet kendilerine geldiklerinde, dolapta bir bebek ve banyoda bir kaplan bulurlar. Ama düğünü yapması gereken en iyi arkadaşları Doug\'ın yerini bir türlü bulamazlar. Çılgınca Doug\'ı aramaya başlayan üçlü, akşamdan kalma bir halde kiliseye zamanında yetişmeye çalışır.', NULL),
(94, 'The Royal Tenenbaums', 'Wes Anderson', 2001, 'Komedi', 'afisler/5xw30y0pSaMtTcuZW5VaQPiR8qb-0-1000-0-1500-crop.jpg', '2025-01-01 12:29:08', 'Aile bir kelime değildir... Bir cümledir.\r\nRoyal Tenenbaum ve eşi Etheline\'in üç çocukları oldu ve sonra ayrıldılar. Üç çocuk da olağanüstüdür - hepsi de dahidir. Genç Tenenbaum\'ların parlaklığına dair neredeyse tüm anılar daha sonra yirmi yıllık ihanet, başarısızlık ve felaketle silindi. Bunların çoğunun babalarının suçu olduğu düşünülüyordu. “The Royal Tenenbaums”, ailenin yakın bir kış mevsiminde aniden ve beklenmedik bir şekilde yeniden bir araya gelişinin öyküsüdür.', NULL),
(95, 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb', 'Stanley Kubrick', 1964, 'Savaş', 'afisler/51218-dr-strangelove-or-how-i-learned-to-stop-worrying-and-love--0-1000-0-1500-crop.jpg', '2025-01-01 12:30:08', 'Sıcak hat gerilim komedisi.\r\nÇılgın General Jack D. Ripper\'ın Sovyetler Birliği\'ne nükleer saldırı başlatmasının ardından, politikacılar, generaller ve bir Rus diplomatla dolu bir savaş odası çılgınca nükleer saldırıyı durdurmaya çalışır.', NULL),
(96, 'Inside Llewyn Davis', 'Joel Coen, Ethan Coen', 2013, 'Müzikal', 'afisler/73367-inside-llewyn-davis-0-1000-0-1500-crop.jpg', '2025-01-01 12:31:28', '1960\'ların başında Greenwich Village\'da yaşayan yetenekli ama uçarı folk müzisyeni Llewyn Davis para, ilişkiler ve belirsiz geleceğiyle mücadele etmektedir.', NULL),
(97, 'Sound of Metal', 'Darius Marder', 2019, 'Müzikal', 'afisler/432004-sound-of-metal-0-1000-0-1500-crop.jpg', '2025-01-01 12:31:59', 'Müzik onun dünyasıydı. Sonra sessizlik yeni bir dünya ortaya çıkardı.\r\nMetal davulcusu Ruben işitme duyusunu kaybetmeye başlar. Bir doktor ona durumunun daha da kötüleşeceğini söylediğinde, kariyerinin ve hayatının bittiğini düşünür. Kız arkadaşı Lou, eski bağımlının sağırlara yönelik bir rehabilitasyon merkezine yatmasını sağlar ve bunun nüksetmesini önleyeceğini ve yeni hayatına uyum sağlamasına yardımcı olacağını umar. Olduğu gibi karşılanıp kabul edildikten sonra Ruben, yeni normali ile bir zamanlar bildiği hayat arasında seçim yapmak zorunda kalır.', NULL),
(98, '8 Mile', 'Curtis Hanson', 2002, 'Müzikal', 'afisler/dXzTrKwpbLpCqn8O70FUUhNbYQT-0-1000-0-1500-crop.jpg', '2025-01-01 12:32:38', 'Her an başka bir şans\r\nJimmy Smith, Jr. için hayat, umudu canlı tutmak için verilen günlük bir mücadeledir. Detroit\'in canlı müzik sahnesinde hayallerini besleyen Jimmy, kendi sesini bulmak ve kafiyelerin hüküm sürdüğü, efsanelerin doğduğu ve her anın başka bir şans olduğu bir dünyada kendine bir yer edinmek için olağanüstü bir kişisel mücadele veriyor.', NULL),
(99, 'Sing Street', 'John Carney', 2016, 'Müzikal', 'afisler/s0C78plmx3dFcO3WMnoXCz56FiN-0-1000-0-1500-crop.jpg', '2025-01-01 12:33:07', 'Erkek kızla tanışır. Kız etkilenmez. Çocuk müzik grubu kurar.\r\n1980\'lerde Dublin\'de büyüyen bir çocuk, hoşlandığı gizemli kızı etkilemek için bir müzik grubu kurarak gergin aile hayatından kaçar.', NULL),
(100, 'Knives Out', 'Rian Johnson', 2019, 'Gizem', 'afisler/475370-knives-out-0-1000-0-1500-crop.jpg', '2025-01-01 12:34:51', 'Herhangi biri yapmış olabilir.\r\nÜnlü polisiye roman yazarı Harlan Thrombey 85. doğum gününden hemen sonra malikanesinde ölü bulunduğunda, meraklı ve nazik Dedektif Benoit Blanc gizemli bir şekilde soruşturma için görevlendirilir. Blanc, Harlan\'ın işlevsiz ailesinden sadık çalışanlarına kadar, Harlan\'ın zamansız ölümünün ardındaki gerçeği ortaya çıkarmak için kırmızı saptırmalar ve kendine hizmet eden yalanlardan oluşan bir ağın içinden geçer.', NULL),
(101, 'Nope', 'Jordan Peele', 2022, 'Gizem', 'afisler/682547-nope-0-1000-0-1500-crop.jpg', '2025-01-01 12:35:19', 'Kötü bir mucize nedir?\r\nKaliforniya\'nın iç kesimlerindeki ıssız bir vadide yaşayanlar tekinsiz ve tüyler ürpertici bir keşfe tanık olurlar.', NULL),
(102, 'Donnie Darko', 'Richard Kelly', 2001, 'Gizem', 'afisler/nmb4QhCRmdfNP6rgb81yUFgI83l-0-1000-0-1500-crop.jpg', '2025-01-01 12:35:44', '28 gün, 6 saat, 42 dakika, 12 saniye... İşte o zaman dünya sona erecek.\r\nTuhaf bir kazadan kıl payı kurtulan sorunlu bir genç, kendisini bir dizi suç işlemeye yönlendiren büyük bir tavşanın hayalleriyle boğuşmaktadır.', NULL),
(103, 'The Lion King', ' Roger Allers, Rob Minkoff', 1994, 'Aile', 'afisler/ztuEReeV6ofpU1HxUV9AsR6aLoe-0-1000-0-1500-crop.jpg', '2025-01-01 12:37:14', 'En büyük macera, Yaşam Çemberi\'ndeki yerimizi bulmaktır.\r\nGenç aslan prens Simba, babası gaspçı amcası tarafından öldürüldüğünde kaçar. İhanet ve trajediden yıllar sonra, yetişkin ve olgun Simba tahtta hak ettiği yeri almak için geri döner.', NULL),
(104, 'The Wild Robot', 'Chris Sanders', 2024, 'Aile', 'afisler/1071196-the-wild-robot-0-1000-0-1500-crop.jpg', '2025-01-01 12:37:44', 'Gerçek doğanızı keşfedin.\r\nBir gemi kazasının ardından Roz adlı akıllı bir robot ıssız bir adada mahsur kalır. Zorlu ortamda hayatta kalmak için Roz adadaki hayvanlarla bağ kurar ve yetim bir kaz yavrusuna bakar.', NULL),
(105, 'The Polar Express', 'Robert Zemeckis', 2004, 'Aile', 'afisler/48883-the-polar-express-0-1000-0-1500-crop.jpg', '2025-01-01 12:38:14', 'Bu tatil sezonunda... inanın.\r\nŞüpheci bir çocuk Kuzey Kutbu\'na giden sıra dışı bir tren yolculuğuna çıktığında, ona inananlar için hayatın mucizesinin asla kaybolmadığını gösteren bir kendini keşfetme yolculuğuna çıkar.', NULL),
(106, 'The Iron Giant', 'Brad Bird', 1999, 'Aile', 'afisler/46280-the-iron-giant-0-1000-0-1500-crop.jpg', '2025-01-01 12:38:39', 'Uzaydan geldi!\r\nEkim 1957\'de Maine eyaletindeki küçük Rockwell kasabasında, dev bir metal makine dokuz yaşındaki bir çocukla arkadaş olur ve sonunda insanları kendi korkularından ve önyargılarından bencilce kurtararak insanlığını bulur.', NULL);

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `users`
--

CREATE TABLE `users` (
  `id` int NOT NULL,
  `username` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Tablo döküm verisi `users`
--

INSERT INTO `users` (`id`, `username`, `password`, `created_at`) VALUES
(1, 'admin', '$2y$10$7k2knsLjX5ASM140Uz.r4O5z8/XP3uesDedu0KLXNd1u.kuDg0oIK', '2024-10-23 20:28:46'),
(5, 'serkan', '$2y$10$gVJWJAd.GPPeINlD3s2WuuJ2fWR0iG0JQyNmerCb/NbOfjJUPcYJu', '2024-10-25 17:43:24'),
(6, 'fred', '$2y$10$wny7WL4typpRaXpI5EoTc.cLxZzXydwnrH68YkxkWrhFUnp2LZR.W', '2025-01-05 18:29:47');

--
-- Dökümü yapılmış tablolar için indeksler
--

--
-- Tablo için indeksler `filmler`
--
ALTER TABLE `filmler`
  ADD PRIMARY KEY (`id`),
  ADD KEY `user_id` (`user_id`);

--
-- Tablo için indeksler `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `username` (`username`);

--
-- Dökümü yapılmış tablolar için AUTO_INCREMENT değeri
--

--
-- Tablo için AUTO_INCREMENT değeri `filmler`
--
ALTER TABLE `filmler`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=107;

--
-- Tablo için AUTO_INCREMENT değeri `users`
--
ALTER TABLE `users`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

--
-- Dökümü yapılmış tablolar için kısıtlamalar
--

--
-- Tablo kısıtlamaları `filmler`
--
ALTER TABLE `filmler`
  ADD CONSTRAINT `filmler_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
